source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'mechanize'
gem 'activerecord'
gem 'mysql2'
gem 'daemon-spawn'
gem 'capistrano'
gem 'thin'
gem 'rack'
gem 'rack-flash3'
gem 'pluginfactory'
gem 'whenever'
gem 'fluent-logger'
gem 'rake'
gem 'capistrano-ext'
gem 'capistrano-rbenv'
