#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

$LOAD_PATH << File.dirname(__FILE__)+'/lib'
require 'webwalker'
require 'daemon_spawn'

include WebWalker

command = ARGV.shift

case command
when 'one'
  pp Handler.walk( ARGV[0], ARGV[1] ).result

when 'add'
  ARGV.each { |x| Handler.add_url Project.new(x), x }

when 'do_one'
  ARGV.each { |x| Handler.walk_one x.to_i }

when 'all'
  WebWalker::Handler.walk_around

when 'zip'
  ARGV.each do |x|
    proj = Project.find(x.to_i)
    puts proj.zip
  end

when 'daemon'   # daemon化する
  class WalkerDaemon < DaemonSpawn::Base
    def start( args )
      puts 'start'
      while true
        WebWalker::Handler.walk_around
        sleep 1
      end
    end
    def stop
      puts 'stoped'
    end
  end

  opt = { 
    log_file: '/var/walker/walker.log', 
    pid_file:'/var/walker/walker.pid', 
    sync_log: true,
    working_dir: File.dirname(__FILE__)
  }
  WalkerDaemon.spawn! opt, ARGV

when 'cron'
  Handler.cron

when nil
  puts "Usage: ww add|one|all|daemon"
else
  puts "unknown command #{command}"
  exit 1
end
